### ISSUE TITLE
Use Laravel Blade templates in Plugin

### ISSUE THREAD

**Issue by wdebusschere** [lukasleitsch/kirby-blade#14]
We have developed a custom blocks plugin, it would be very handy if we could also store the default blade templates inside the plugin. Thank you.

**Comment by lukasleitsch** [comment]
Block templates will be loaded via the snippets function and Kirby currently don't offer a way to register a template engine for snippets.

You could load a blade template inside a snippet via the [`component()`](https://github.com/lukasleitsch/kirby-blade/blob/main/helpers.php#L15) helper.

**Comment by wdebusschere** [comment]
@lukasleitsch Could you elaborate a bit more this approach if you have some time? Thank you.

**Comment by fabianmichael** [comment]
@wdebusschere I need this feature myself and just looked that up: Turns out, (newer versions of?) Kirby allow a custom snippets component. https://getkirby.com/docs/reference/plugins/components/snippet

I’ll take care of this. :-)

**Comment by fabianmichael** [comment]
See #15

**Comment by lukasleitsch** [comment]
@wdebusschere Feature is merged to main. Please give it a shot.

- Blade files in the snippets folder will be loaded
- You can register blade template and blade snippets in your plugin.

**Comment by wdebusschere** [comment]
@fabianmichael @lukasleitsch Thanks to both!
This works if i call the snippet with `<?php snippet('xxxxx') ?>` but it would be better if could use Blade's @include directive.. Let me know if possible if not i'll start converting :)

FYI `@include('xxxxx')`gives  `View [xxxxx] not found.`

**Comment by fabianmichael** [comment]
@wdebusschere You can also use `@snippet('…')`. We try to make the plugin to feel as "Kirby-ish" as possible (= flat learning curve for Kirby users), so I don’t see any reason for adding another directive. If you want to use `@snippet('…')` instead, you can always register a custom directive on your own.
