### ISSUE TITLE
Allow plugins to register blade components

### ISSUE THREAD

**Issue by fabianmichael** [lukasleitsch/kirby-blade#18]
Plugins should be able to register components and coresponding classes and templates. Related to #10

**Comment by samlinck** [comment]
Is this possible yet? Also is there a way to register anonymous components? @fabianmichael

**Comment by fabianmichael** [comment]
@samlinck Don’t know to be honest, since I personally habe moved away from using blade in new projects. But as far as I remember I used this in some form. But since I don’t plan to make any further contributions to this plugin and I don’t think that @lukasleitsch has the time to bring this issue forward, I am closing this issue now. Sorry.
