### ISSUE TITLE
3.8 compatibility

### ISSUE THREAD

**Issue by afbora** [lukasleitsch/kirby-blade#26]
- Missing composer.json version
- Plugin name doesn't match with getkirby.com

https://github.com/getkirby/kirby/issues/4713

**Comment by lukasleitsch** [comment]
Version was added to composer.json.

@afbora Do you know if it is possible to change the name on getkirby.com? I'm using `leitsch` as my vendor name (Namespace and packagist). Would be great if getkirby.com could use the same vendor name.

**Comment by afbora** [comment]
✅ Done. Thank you 🎉

**Comment by lukasleitsch** [comment]
Thanks for renaming it.
