### ISSUE TITLE
Kirby 3.9.2: Snippets with slots

### ISSUE THREAD

**Issue by wdebusschere** [lukasleitsch/kirby-blade#27]
Is this difficult to add to the blade template engine?

**Comment by lukasleitsch** [comment]
Could you give an example?

Snippets are not really needed with blade. You could [include a Blade-Template](https://laravel.com/docs/10.x/blade#including-subviews)  or use [blade components](https://laravel.com/docs/10.x/blade#components).

**Comment by wdebusschere** [comment]
@lukasleitsch Indeed! We use the blade components, works great!
