### ISSUE TITLE
Custom directive with more than one parameter

### ISSUE THREAD

**Issue by hansipete** [lukasleitsch/kirby-blade#28]
I'm struggling with creating a custom directive like this one: `@my_svg('/assets/Wortmarke.svg', 'bg-blue')`

The parameters seem get passed as one string in the config.php. Is that expected behaviour? I was assuming that I will have a `function ($path, $class){ ... }` for making use of them...
 
Anyone else having trouble with multiple parameters? Also it seems that I need to clear the cache in `storage/cache` to have updates (custom directive) to my config.php reliably reflected when reloading.

**Comment by lukasleitsch** [comment]
Yes, you are right. You can only pass one parameter to a custom directive. `$expression` is a string and contains both parameters.

Laravel Docs: https://laravel.com/docs/10.x/blade#extending-blade

Maybe this thread from laracasts helps you: https://laracasts.com/discuss/channels/laravel/how-to-do-this-blade-directive

Yes, you have to clear the cache after updating a directive. From the Laravel docs:

> After updating the logic of a Blade directive, you will need to delete all of the cached Blade views. The cached Blade views may be removed using the view:clear Artisan command.
