### ISSUE TITLE
Directives not rendering when passing translations in index.php

### ISSUE THREAD

**Issue by ceesvanegmond** [lukasleitsch/kirby-blade#33]
**Issue Description:**

Hello! I'm encountering an issue while working with the latest Kirby starterkit. The problem arises when I add custom translations to the `index.php` file as shown below:

```php
$kirby = new Kirby([
    // ...
    'languages' => [
        'nl' => [
            'code' => 'nl',
            'default' => true,
            'url' => '/nl',
            'direction' => 'ltr',
            'locale' =>  'nl_NL',
            'name' =>  'Nederlands',
            'translations' => Yaml::decode(F::read(kirby()->root('languages') . '/nl.yaml')) // This line causes the issue
        ],
    ]
]);
```

**Issue Details:**

The issue occurs when using custom translations defined in the `index.php`. Directives fail to render properly. Instead of rendering the expected output, such as the content of a directive like `@greeting`, the template simply displays `@greeting` as static text.

**Expected Behavior:**

I expect the Blade template to render the contents of the directives correctly, such as `@greeting`, when custom translations are added to the `index.php` file.

**Reproduction Steps:**

1. Clone the latest Kirby starterkit.
2. Add the custom translations as shown in the code snippet above to the `index.php` file.
3. Attempt to render a directive, for example `@greeting`, in a Blade template.

**Actual Behavior:**

The directive, such as `@greeting`, is not rendered as expected. Instead, the template displays the directive name as static text (`@greeting`).

**Additional Information:**

This behavior seems unexpected, as removing the `'translations'` line from the code snippet resolves the issue, and the directives render correctly. It appears that the presence of custom translations in the `index.php` file is somehow affecting the rendering of Blade directives.

Any guidance or insight into resolving this issue would be greatly appreciated! Thank you for your help.

---

Feel free to adjust any details as needed based on your specific situation or additional context you may have.

**Comment by lukasleitsch** [comment]
You example calls Kirby twice: The first time with `kirby()->root()` and the second onetime with `new Kirby()`.

The result of two calls is that the hook `system.loadPlugins:after` is also called twice. The Blade Plugin uses this hook to register the directives.

In the `index.php`, you need to call Kirby only once, and the parameters can be filled with plain PHP functions.

As reference, see: https://getkirby.com/docs/guide/configuration/custom-folder-setup#public-and-private-folder-setup__index-php

A potential solution could be this setup:

```php
echo (new Kirby([
    'languages' => [
        'nl' => [
            'code' => 'nl',
            'default' => true,
            'url' => '/nl',
            'direction' => 'ltr',
            'locale' =>  'nl_NL',
            'name' =>  'Nederlands',
            'translations' => Yaml::decode(F::read(dirname(__FILE__) . '/nl.yaml'))
        ],
    ]
]))->render();
```
