### ISSUE TITLE
Documentation on how to use components

### ISSUE THREAD

**Issue by mxub** [lukasleitsch/kirby-blade#37]
Hey everyone,

Firstly: thank you for providing this plugin. 

The readme mentions 

> You can use the power of Blade like Layouts, Forms, Sub-Views, Components, Directives and your custom if statements.

I'm mostly interested in creating components for better work with tailwind. Sadly I don't understand how to get that working.

A little more examples in the documentation would be awesome so that someone like me can get started right away.

My goal for now:

I want a `<x-hello />` tag that inserts `<span>Hello World</span>`

- What would be the preferred setup within Kirby?

> When writing components for your own application, components are automatically discovered within the app/View/Components directory and resources/views/components directory. _-- [Blade Documentation](https://laravel.com/docs/9.x/blade#manually-registering-package-components)_

- Is there an analogous directory in the templates folder?

Any pointers on where to start would be highly appreciated. It feels like it belongs somewhat to #20 but I would need some pointers to start becoming helpful...

## File Structure as I would imagine
```
site/Templates/
. default.blade.php
. View/Componens/
. . hello.blade.php
```

**Comment by lukasleitsch** [comment]
Yes, these features are not really well-documented. I created a PR #38 with more details about using components.

Please have a look and try to use it. Feedback is appreciated.

**Comment by lukasleitsch** [comment]
The updated README is now available in the main branch.

https://github.com/lukasleitsch/kirby-blade/tree/main?tab=readme-ov-file#anonymous-components
