### ISSUE TITLE
Cannot update to 3.0.3

### ISSUE THREAD

**Issue by wdebusschere** [lukasleitsch/kirby-blade#40]
composer.json requires leitsch/kirby-blade ^3.0.3, found leitsch/kirby-blade[dev-feature/components-registry, dev-tobimori/main, dev-main, dev-readme, dev-fabianmichael-patch-1, 1.0, ..., 1.9.2, 2.0.0, ..., 2.3.5, 3.0.0, 3.0.2] but it does not match the constraint.

**Comment by lukasleitsch** [comment]
Should be fixed with 3.0.4
