### ISSUE TITLE
Support dynamic components syntax

### ISSUE THREAD

**Issue by fabianmichael** [lukasleitsch/kirby-blade#5]
Currently, the plugin does not support the `<x-dynamic-component :component="…" />` syntax. We should think about adding it.

See https://www.amitmerchant.com/dynamic-blade-components-in-laravel-8/

**Comment by lukasleitsch** [comment]
Dynamic component syntax is with the latest version possible.

**Comment by fabianmichael** [comment]
@lukasleitsch Merci! :-)
