### ISSUE TITLE
Blade for snippets and blocks

### ISSUE THREAD

**Issue by iskrisis** [lukasleitsch/kirby-blade#9]
Hi, is there way to use blade in snippets and for blocks?
If not is there some way to use components in non blade templates? Maybe some global function that would render them?

**Comment by lukasleitsch** [comment]
> is there way to use blade in snippets

An alternative or replacement for snippets are [subviews](https://laravel.com/docs/9.x/blade#including-subviews) or [components](https://laravel.com/docs/9.x/blade#components).

> and for blocks?

Currently, not supported.

> If not is there some way to use components in non blade templates?

You could use the render method to render a component inside a php template.

```php
<?= \Illuminate\Support\Facades\Blade::render('<x-alert />') ?>
```

Or you could use the `component()` helper: https://github.com/lukasleitsch/kirby-blade/blob/main/helpers.php#L15

**Comment by iskrisis** [comment]
@lukasleitsch very helpful thank you so much!

**Comment by lukasleitsch** [comment]
@iskrisis You're welcome
